Repository wecode-bootcamp-korea/23-1st-Gaebalance-frontend, pull requests merged in 2021-08, with the labels that each got.

#5 Add: Footer 작업완료
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: Status: 리뷰 요청

#3 [황대웅] Add: 제품 상세페이지 제품정보 부분 화면구현 완료
  .vscode/settings.json
  public/data/product.json
  public/images/ProductDetail/mockProduct.jpg
  public/images/ProductDetail/mockProduct.png
  public/images/ProductDetail/tag-best.png
  public/images/ProductDetail/tag-new.png
  public/images/ProductDetail/tag-onlineonly.png
  public/index.html
  src/Routes.js
  src/index.js
  src/pages/ProductDetail/OrderListBox.js
  src/pages/ProductDetail/OrderListBox.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/ProductInfoBox.js
  src/pages/ProductDetail/ProductinfoBox.scss
  src/pages/ProductDetail/SizePicker.js
  src/pages/ProductDetail/SizePicker.scss
  src/styles/common.scss
Labels: Status: 수정 요청

#2 [김가영] Modify: 코드 리뷰 사항 수정
  public/images/gaebalance.md
  public/images/kayoung/Icon/ic-bottom.png
  public/images/kayoung/Icon/ic-half-star.png
  public/images/kayoung/Icon/ic-right.png
  public/images/kayoung/Icon/ic-star.png
  public/images/kayoung/Icon/tag-best.png
  public/images/kayoung/Icon/tag-new.png
  public/images/kayoung/Icon/tag-onlineonly.png
  public/images/kayoung/img-product.png
  public/images/kayoung/img-product2.jpeg
  public/index.html
  src/Routes.js
  src/config.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/ProductLists/Components/Dropdown.js
  src/pages/ProductLists/Components/Dropdown.scss
  src/pages/ProductLists/Components/ProductCard.js
  src/pages/ProductLists/Components/ProductCard.scss
  src/pages/ProductLists/Components/SearchFilter.js
  src/pages/ProductLists/Components/SearchFilter.scss
  src/pages/ProductLists/Components/SearchFilterData.json
  src/pages/ProductLists/ProductLists.js
  src/pages/ProductLists/ProductLists.scss
Labels: Status: 수정 요청

#6 ADD:Nav 작업 완료
  src/Routes.js
  src/asset/-image/logo.png
  src/asset/-image/loupe.png
  src/asset/-image/user.png
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/Nav/Category.js
  src/components/Nav/Nav/Category.scss
  src/components/Nav/Nav/Nav.js
  src/components/Nav/Nav/Nav.scss
  src/pages/Main/Main.js
Labels: Status: Conflict 해결 요청

#8 ADD: 로그인 작업 완료
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/styles/common.scss
Labels: Status: 리뷰 요청

#9 [이현준] Add: 메인화면 구현완료
  public/images/image.png
  src/Routes.js
  src/assets/images/left.png
  src/assets/images/right.png
  src/pages/Main/Allshop/Allshop.js
  src/pages/Main/Allshop/Allshop.scss
  src/pages/Main/Gbnow/Gbnow.js
  src/pages/Main/Gbnow/Gbnow.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/SlideMenu/SlideMenu.js
  src/pages/Main/SlideMenu/SlideMenu.scss
Labels: Status: 리뷰 요청

#7 [이현준] Add: 회원가입 작업 완료
  src/Routes.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav/Category.scss
  src/config.js
  src/pages/Checkbox/Checkbox.js
  src/pages/Checkbox/Checkbox.scss
  src/pages/Join/Join.js
  src/pages/Join/Join.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: Status: 리뷰 요청

#10 [이현준] Add: 로그인 API 연결 완료
  src/Routes.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#13 [이현준] Add: main.js 최종수정
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#14 [황대웅] Add: 장바구니 페이지 완료
  src/Routes.js
  src/config.js
  src/pages/ProductDetail/OrderListBox.js
  src/pages/ProductDetail/OrderListBox.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/ProductInfoBox.js
  src/pages/ProductDetail/SizePicker.scss
  src/pages/ShoppingCart/AddCart.js
  src/pages/ShoppingCart/AddCart.scss
  src/pages/ShoppingCart/ShoppingCart.js
  src/pages/ShoppingCart/ShoppingCart.scss
Labels: Status: 리뷰 요청

#15 ADD/MODIFY: 다중 필터링 기능, 페이지네이션(더보기) 구현 등
  public/images/main.jpg
  src/Routes.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav/Category.js
  src/components/Nav/Nav/Nav.js
  src/config.js
  src/pages/Join/Join.js
  src/pages/Login/Login.js
  src/pages/Main/Allshop/Allshop.scss
  src/pages/Main/Main.scss
  src/pages/Main/SlideMenu/SlideMenu.js
  src/pages/Main/SlideMenu/SlideMenu.scss
  src/pages/ProductDetail/OrderListBox.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductLists/Components/Dropdown.js
  src/pages/ProductLists/Components/ProductCard.js
  src/pages/ProductLists/Components/ProductCard.scss
  src/pages/ProductLists/Components/SearchFilter.js
  src/pages/ProductLists/Components/SearchFilter.scss
  src/pages/ProductLists/Components/SearchFilterData.json
  src/pages/ProductLists/ProductLists.js
  src/pages/ProductLists/ProductLists.scss
  src/pages/ShoppingCart/AddCart.js
  src/pages/ShoppingCart/ShoppingCart.js
  src/pages/ShoppingCart/ShoppingCart.scss
  src/styles/common.scss
Labels: Status: 리뷰 요청
